swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Petstore
 
host: 127.0.0.1:8000
basePath: /api
tags:
  - name: providers
    description: CRUD on providers
  - name: service_areas
    description: CRUD on service areas
  - name: check
    description: Get all the service areas containing a point
schemes:
  - http
paths:
  /providers:
    post:
      tags:
        - providers
      summary: Add a new provider
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Provider object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/ProviderSchema'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/ProviderResponseSchema'
    get:
      tags:
        - providers
      summary: Get all providers
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/ProviderResponseSchema'
  /providers/{providerId}:
    get:
      tags:
        - providers
      summary: Get provider by id
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: ID of provider to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ProviderResponseSchema'
    put:
      tags:
        - providers
      summary: Update a provider
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: ID of provider to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Provider object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/ProviderSchema'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ProviderResponseSchema'
    delete:
      tags:
        - providers
      summary: Delete a provider
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: ID of provider to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
  /service_areas/{providerId}:
    get:
      tags:
        - service_areas
      summary: Get all service areas of a provider
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: ID of provider whose service areas to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ServiceAreaResponseSchema'
    post:
      tags:
        - service_areas
      summary: Add a new service area to the provider
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: ID of provider whose service areas to return
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Service area object to be added
          required: true
          schema:
            $ref: '#/definitions/ServiceAreaSchema'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/CreateServiceAreaResponseSchema'
  /service_areas/{providerId}/{serviceAreaId}:
    get:
      tags:
        - service_areas
      summary: Get a service area by id
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: ID of provider who owns the service area
          required: true
          type: integer
          format: int64
        - name: serviceAreaId
          in: path
          description: ID of service area to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ServiceAreaResponseSchema'
        '401':
          description: service area does not belong to the provider
    put:
      tags:
        - service_areas
      summary: Update a service area
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: ID of provider who owns the service area
          required: true
          type: integer
          format: int64
        - name: serviceAreaId
          in: path
          description: ID of service area to be updated
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Updated service area object
          required: true
          schema:
            $ref: '#/definitions/ServiceAreaSchema'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/CreateServiceAreaResponseSchema'
        '401':
          description: service area does not belong to the provider
    delete:
      tags:
        - service_areas
      summary: Delete a service area
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: providerId
          in: path
          description: ID of provider who owns the service area
          required: true
          type: integer
          format: int64
        - name: serviceAreaId
          in: path
          description: ID of service area to be deleted
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
        '401':
          description: service area does not belong to the provider
          
  /check:
    get:
      tags:
        - check
      summary: Get all service area that contain a given lat/lng
      produces:
        - application/json
      parameters:
        - name: lat
          in: query
          description: Latitude of the point
          required: true
          type: number
          format: float
        - name: lng
          in: query
          description: Longitude of the point
          required: true
          type: number
          format: float
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ServiceAreaResponseSchema'
        '401':
          description: service area does not belong to the provider
    

definitions:
  ProviderSchema:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
        format: email
      phone:
        type: string
      lang:
        type: string
      currency:
        type: string
  ProviderResponseSchema:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      email:
        type: string
        format: email
      phone:
        type: string
      lang:
        type: string
      currency:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  ServiceAreaSchema:
    type: object
    properties:
      name:
        type: string
      price:
        type: number
        format: float
      polygon:
        type: array
        items:
          type: array
          items:
            type: integer
            
  CreateServiceAreaResponseSchema:
    type: object
    properties:
      id:
        type: integer
        format: int64
      type:
        type: string
      geometry:
        type: object
        properties:
          type:
            type: string
          coordinates:
            type: array
            items:
              type: array
              items:
                type: integer
      properties:
        type: object
        properties:
          name:
            type: string
          price:
            type: number
            format: float
          created_at:
            type: string
            format: date-time
          updated_at:
            type: string
            format: date-time
          provider:
            type: integer
            format: int64
            
  ServiceAreaResponseSchema:
    type: object
    properties:
      type:
        type: string
      features:
        type: array
        items:
          $ref: '#/definitions/CreateServiceAreaResponseSchema'
      geometry:
        type: object
        properties:
          type:
            type: string
          coordinates:
            type: array
            items:
              type: array
              items:
                type: integer
      properties:
        type: object
        properties:
          name:
            type: string
          price:
            type: number
            format: float
          created_at:
            type: string
            format: date-time
          updated_at:
            type: string
            format: date-time
          provider:
            type: integer
            format: int64
        
